[package]
name = "primitives"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[lib]
doctest = false

[dependencies]
rustc-hex.workspace = true
bitcoin_hashes.workspace = true
byteorder.workspace = true
uint.workspace = true
