name: Install Dependencies
description: Install non-cargo dependencies in an OS-agnostic way

inputs:
  deps:
    description: "Dependencies to install (format: ('list' 'of' 'dependencies'))."
    required: true
  temp:
    description: "A temporary directory path that can be used to store the installed binaries if needed."

# NOTE: Don't install binaries in the project directory because the directory might be checked out later.
runs:
  using: 'composite'
  steps:
    - name: Download protoc (Linux)
      if: runner.os == 'Linux' && contains(inputs.deps, 'protoc')
      uses: ./.github/actions/download-and-verify
      with:
        url: "https://github.com/protocolbuffers/protobuf/releases/download/v25.3/protoc-25.3-linux-x86_64.zip"
        output_file: "protoc-25.3-linux-x86_64.zip"
        checksum: "f853e691868d0557425ea290bf7ba6384eef2fa9b04c323afab49a770ba9da80"

    - name: Install protoc (Linux)
      env:
        TMP: ${{ inputs.temp || runner.temp }}
      if: runner.os == 'Linux' && contains(inputs.deps, 'protoc')
      shell: bash
      run: |
        unzip protoc-25.3-linux-x86_64.zip -d "$TMP/protobuf"
        echo "$TMP/protobuf/bin" >> $GITHUB_PATH

    - name: Download protoc (MacOS)
      if: runner.os == 'macOS' && contains(inputs.deps, 'protoc')
      uses: ./.github/actions/download-and-verify
      with:
        url: "https://github.com/protocolbuffers/protobuf/releases/download/v25.3/protoc-25.3-osx-x86_64.zip"
        output_file: "protoc-25.3-osx-x86_64.zip"
        checksum: "247e003b8e115405172eacc50bd19825209d85940728e766f0848eee7c80e2a1"

    - name: Install protoc (MacOS)
      env:
        TMP: ${{ inputs.temp || runner.temp }}
      if: runner.os == 'macOS' && contains(inputs.deps, 'protoc')
      shell: bash
      run: |
        unzip protoc-25.3-osx-x86_64.zip -d "$TMP/protobuf"
        echo "$TMP/protobuf/bin" >> $GITHUB_PATH


    - name: Download protoc (Windows)
      uses: ./.github/actions/download-and-verify
      with:
        url: "https://github.com/protocolbuffers/protobuf/releases/download/v25.3/protoc-25.3-win64.zip"
        output_file: "protoc-25.3-win64.zip"
        checksum: "d6b336b852726364313330631656b7f395dde5b1141b169f5c4b8d43cdf01482"

    - name: Install protoc (Windows)
      env:
        TMP: ${{ inputs.temp || runner.temp }}
      if: runner.os == 'Windows' && contains(inputs.deps, 'protoc')
      shell: powershell
      run: |
        7z x protoc-25.3-win64.zip -o"$TMP\protobuf"
        echo "$TMP\protobuf\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install libudev (Linux)
      if: runner.os == 'Linux' && contains(inputs.deps, 'libudev')
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libudev-dev

    - name: Install python3
      uses: actions/setup-python@v5
      if: contains(inputs.deps, 'python3')
      with:
        python-version: 3

    - name: Install `paramiko` pip package
      if: contains(inputs.deps, 'paramiko')
      shell: bash
      run: pip install paramiko
